# Generated by Django 4.0.3 on 2022-03-14 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('str_sep', models.CharField(choices=[('SEMICOLON', ';'), ('COMMA', ',')], default='COMMA', max_length=16)),
                ('str_char', models.CharField(choices=[('QUOTE', "'"), ('DOUBLE_QUOTE', '"')], default='DOUBLE_QUOTE', max_length=16)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
            },
        ),
        migrations.CreateModel(
            name='SchemaColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('STRING', 'STRING'), ('FULL_NAME', 'FULL_NAME'), ('INTEGER', 'INTEGER'), ('DATE', 'DATE'), ('COMPANY', 'COMPANY'), ('JOB_ROLE', 'JOB_ROLE')], default='STRING', max_length=128)),
                ('range_from', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('range_to', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fake_csv.csvschema')),
            ],
            options={
                'verbose_name': 'Schema column',
                'verbose_name_plural': 'Schema columns',
            },
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('PROCESSING', 'PROCESSING')], default='PROCESSING', max_length=128)),
                ('file', models.FilePathField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv.csvschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Data',
            },
        ),
    ]
